### ISSUE TITLE
Validation description

### ISSUE THREAD

**Issue by gotanbl** [InfotelGLPI/consumables#9]
I have the latest version of plugin and glpi 9.1.1.
During validation of request for consumable, you have text field where we provide, my opinion, reason for using  or some other information regarding consumable.
After click on validate I have response from glpi, error > consumable validated and onether window with information > operation successfull. Is this some problem or what?
Where in glpi I can see this information, after validation process finished?

**Comment by amma35** [comment]
When the message "consumable validated" appears, validation has been completed. 
The bug comes from the title of the message (Error).

To check whether the validation has been carried out, you must go to the "consumable" -> "consumable request".
![consumable](https://cloud.githubusercontent.com/assets/15138371/23278569/4766ea54-fa12-11e6-85f8-2f8a55207867.PNG)


The message that is specified with validation or refusal is used in the notification.
